server:
  port: 8081
  
spring:
  datasource:
    platform: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crimemanagement
    username: user
    password: mani@132    
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      
      